### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by syun-2466** [syun-2466/protospace-34993#1]
本番環境のURLです、よろしくお願いします。
https://protospace-34993.herokuapp.com/

**Comment by miyu-yamamoto** [comment]
@syun-2466 さん、お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **ログイン・ログアウトの状態に関わらず、プロトタイプ一覧を閲覧できるようにしましょう。**
ログアウト時、プロトタイプ一覧を閲覧することができません
※上記により、ログアウト時の動作は今回行えておりません。次回修正いただけましたら改めて確認させていただきます。


- [x] **コメントを投稿すると、投稿したコメントとその投稿者名が、対象プロトタイプの詳細ページにのみ表示されるようにしましょう。**
コメントを投稿すると全てのプロトタイプ詳細ページに反映してしまいます

- [x] **コメントフォームを空のまま投稿しようとすると、投稿できずにそのページに留まるようにしましょう。**
エラーが表示されます

- [x] **ログイン状態のユーザーであっても、他のユーザーのプロトタイプ編集ページのURLを直接入力して遷移しようとすると、トップページにリダイレクトされるようにしましょう**
他のユーザーが投稿したプロトタイプの編集ページも開けてしまいます

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
